
flib_version=0.2.7
flib_file=8309035

mod_id=examplemod
curse_slug=examplemod
modrinth_id=
curse_id=0
mod_version=0.0.0-SNAPSHOT
mod_name=examplemod
mod_group_id=com.lothrazar.examplemod
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=examplemod
